DROP TABLE IF EXISTS APPRENTICE_PLAYLIST;
DROP TABLE IF EXISTS MASTER_APPRENTICE;
DROP TABLE IF EXISTS INSTITUTIONS;
DROP TABLE IF EXISTS DISCIPLINE;
DROP TABLE IF EXISTS STATUS;
DROP TABLE IF EXISTS ANSWERED_QUESTION;
DROP TABLE IF EXISTS QUESTION;
DROP TABLE IF EXISTS USER_APPRENTICE;
DROP TABLE IF EXISTS USER_MASTER;

CREATE TABLE USER_APPRENTICE(

	ID INT( 64 ) UNSIGNED AUTO_INCREMENT,
	NAME VARCHAR( 64 ) NOT NULL,
	PASSWORD VARCHAR( 64 ) NOT NULL,
	EMAIL VARCHAR( 64 ) NOT NULL,
	TIMEOUT INT( 64 ) UNSIGNED NOT NULL,
	
	PRIMARY KEY( ID, EMAIL )

);

CREATE TABLE USER_MASTER(

	ID INT( 64 ) UNSIGNED AUTO_INCREMENT,
	NAME VARCHAR( 64 ) NOT NULL,
	PASSWORD VARCHAR( 64 ) NOT NULL,
	EMAIL VARCHAR( 64 ) NOT NULL,
	DEGREE VARCHAR( 128 ) NOT NULL,
	INSTITUTION VARCHAR( 128 ) NOT NULL,
	ACCEPTED BOOLEAN NOT NULL,
	
	PRIMARY KEY( ID, EMAIL )

);

CREATE TABLE INSTITUTIONS(

	ID INT( 64 ) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR( 64 ) NOT NULL

);

CREATE TABLE QUESTION(

	ID INT( 64 ) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	TITLE TEXT NOT NULL,
	A TEXT NOT NULL,
	B TEXT NOT NULL,
	C TEXT NOT NULL,
	D TEXT NOT NULL,
	E TEXT NOT NULL,
	CORRECT_ANSWER CHAR NOT NULL,
	AREA INT( 64 ) NOT NULL,
	ACCEPTED BOOLEAN NOT NULL

);

CREATE TABLE DISCIPLINE(

	ID INT( 64 ) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	APPRENTICE_ID INT( 64 ) UNSIGNED NOT NULL,
	MATH_FOCUS INT( 64 ) UNSIGNED NOT NULL,
	SCIENCE_FOCUS INT( 64 ) UNSIGNED NOT NULL,
	LANGUAGE_FOCUS INT( 64 ) UNSIGNED NOT NULL,
	
	FOREIGN KEY( APPRENTICE_ID ) REFERENCES USER_APPRENTICE( ID )

);

CREATE TABLE STATUS(

	ID INT( 64 ) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	APPRENTICE_ID INT( 64 ) UNSIGNED NOT NULL,
	MATH_CORRECT INT( 64 ) UNSIGNED NOT NULL,
	SCIENCE_CORRECT INT( 64 ) UNSIGNED NOT NULL,
	LANGUAGE_CORRECT INT( 64 ) UNSIGNED NOT NULL,
	MATH_WRONG INT( 64 ) UNSIGNED NOT NULL,
	SCIENCE_WRONG INT( 64 ) UNSIGNED NOT NULL,
	LANGUAGE_WRONG INT( 64 ) UNSIGNED NOT NULL,

	FOREIGN KEY( APPRENTICE_ID ) REFERENCES USER_APPRENTICE( ID )

);

CREATE TABLE ANSWERED_QUESTION(

	ID INT( 64 ) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	APPRENTICE_ID INT( 64 ) UNSIGNED NOT NULL,
	QUESTION_ID INT( 64 ) UNSIGNED NOT NULL,

	FOREIGN KEY( APPRENTICE_ID ) REFERENCES USER_APPRENTICE( ID ),
	FOREIGN KEY( QUESTION_ID ) REFERENCES QUESTION( ID )

);

CREATE TABLE MASTER_APPRENTICE(

	ID INT( 64 ) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	APPRENTICE_ID INT( 64 ) UNSIGNED NOT NULL,
	MASTER_ID INT( 64 ) UNSIGNED NOT NULL,
	
	FOREIGN KEY( APPRENTICE_ID ) REFERENCES USER_APPRENTICE( ID ),
	FOREIGN KEY( MASTER_ID ) REFERENCES USER_MASTER( ID )

);

CREATE TABLE APPRENTICE_PLAYLIST(

	ID INT( 64 ) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	APPRENTICE_ID INT( 64 ) UNSIGNED NOT NULL,
	MASTER_ID INT( 64 ) UNSIGNED NOT NULL,
	QUESTION_ID INT( 64 ) UNSIGNED NOT NULL

);

INSERT INTO INSTITUTIONS( NAME ) VALUES( 'Feevale' );
INSERT INTO INSTITUTIONS( NAME ) VALUES( 'Unisinos' );
INSERT INTO INSTITUTIONS( NAME ) VALUES( 'UFRGS' );
INSERT INTO INSTITUTIONS( NAME ) VALUES( 'Unilasalle' );
INSERT INTO INSTITUTIONS( NAME ) VALUES( 'PUCRS' );

SELECT * FROM APPRENTICE_PLAYLIST;
SELECT * FROM MASTER_APPRENTICE;
SELECT * FROM INSTITUTIONS;
SELECT * FROM DISCIPLINE;
SELECT * FROM STATUS;
SELECT * FROM ANSWERED_QUESTION;
SELECT * FROM QUESTION;
SELECT * FROM USER_APPRENTICE;
SELECT * FROM USER_MASTER;
